### PR TITLE
#389 rewrite Autocomplete component

### LINKED ISSUE #389: fix remote data example of Autocomplete

### PR DESCRIPTION
**Pull request by TheHadiAhmadi**

### CODE REVIEW

**Comment by pournasserian** [comment]
@TheHadiAhmadi there are still some issues:

The code has console.log
image

When the user selects an item, the dropdown items won't be closed:
image

When it is disabled, if user clicks on the input, a tiny-empty dropdown container will be shown:
image

Many items are shown without scrolling feature inside the continer:
image
Also, above example has not a good UI (margin).

**Comment by TheHadiAhmadi** [comment]
@pournasserian it's ready to review

**Comment by mhmdtaherian** [comment]
There are still a couple of issues with Autocomplete
1. when we click on it, the dropdown items will blink (show then hide quickly)
autocomplete-1

2. When Autocomplete is focused if we type something it won't work. We need to click on it again to show the items then it will work.
autocomplete-2

3. In the Input Event sample when we write something, it works and binds the data but when we delete the input the type another thing, it will crash.
autocomplete-3

**Comment by TheHadiAhmadi** [comment]
@mhmdtaherian to fix bug number 1, we should merge #396, and for number 3 I updated the example.

I didn't noticed bug number 2, I tested and input focus always worked. 
also updated some events. please test it again.

**Pull request merged**
