### PR TITLE
213 develop popup component

### LINKED ISSUE #19: Initial commit for Tooltip

### LINKED ISSUE #133: Develop Tooltip component

### LINKED ISSUE #213: Develop Popup Component

### LINKED ISSUE #217: Develop Popover component

### PR DESCRIPTION
**Pull request by TheHadiAhmadi**

### CODE REVIEW

**Comment by pournasserian** [comment]
@TheHadiAhmadi what is the usage for Popup component? There is no documentation.

**Comment by TheHadiAhmadi** [comment]
@pournasserian we are using it internally and user doesn't need to use it directly.

Do you know any usage other than Popover, tooltip and drop-down menu?

**Comment by pournasserian** [comment]
@TheHadiAhmadi got it. 
In Popover component, I prefer to have a `show` boolean prop rather than using component sibling. What do you think?

**Comment by pournasserian** [comment]
> @TheHadiAhmadi got it. In Popover component, I prefer to have a `show` boolean prop rather than using component sibling. What do you think?

Similar to Modal, Offcanvas, etc.

**Comment by TheHadiAhmadi** [comment]
@pournasserian What if we support both use cases? 
We need to have target element (for calculating placement).
to manage open/close states we can have `trigger` property (hover, focus,click) and also `show` boolean property

**Comment by pournasserian** [comment]
> @pournasserian What if we support both use cases? We need to have target element (for calculating placement). to manage open/close states we can have `trigger` property (hover, focus,click) and also `show` boolean property

Got it. That's fine for now.

**Pull request merged**
