### PR TITLE
#201 Add Slider Component

### LINKED ISSUE #139: Develop RangeSlider component

### LINKED ISSUE #201: Add Slider component

### LINKED ISSUE #202: Add RangeSlider component

### PR DESCRIPTION
**Pull request by TheHadiAhmadi**

### CODE REVIEW

**Comment by TheHadiAhmadi** [comment]
close #202

**Comment by pournasserian** [comment]
@TheHadiAhmadi 
Please make these changes:

- connect property from Slider (it doesn't make sense). We may have another property (like reverse). What do you think?
- Add FormSlider and its documentation
- Add documentation for FormSlider
- Add Slider and FormSlider menus to documentation website's sidebar

**Comment by TheHadiAhmadi** [comment]
@pournasserian what do you think if we use  `connectWithNext` and `connectWithPrevious` boolean props for SliderKnob instead of `connect`? 

or `connectUpper` and `connectLower`

**Comment by pournasserian** [comment]
> @pournasserian what do you think if we use `connectWithNext` and `connectWithPrevious` boolean props for SliderKnob instead of `connect`?
> 
> or `connectUpper` and `connectLower`

Please write an example for each usage here

**Comment by TheHadiAhmadi** [comment]
@pournasserian 
example for `connectWithNext` and `connectWithPrevious`
```svelte
<script lang="ts">
    import {Slider, SliderKnob} from 'yesvelte'

</script>

<Slider>
    <SliderKnob connectWithNext bind:value={minPrice}/>
    <SliderKnob bind:value={maxPrice}/>
</Slider>

<Slider>
    <SliderKnob connectWithNext bind:value={minPrice}/>
    <SliderKnob bind:value={maxPrice}/>
    <SliderKnob bind:value={minPrice2}/>
    <SliderKnob connectWithPrevious bind:value={maxPrice2}/>
</Slider>

```

example from `connectLower` and `connectUpper`
```svelte
<script lang="ts">
    import {Slider, SliderKnob} from 'yesvelte'

</script>

<Slider>
    <SliderKnob connectLower bind:value={minPrice}/>
</Slider>

<!-- -->
<Slider>
    <SliderKnob connectUpper bind:value={minPrice}/>
</Slider>
```

**Comment by TheHadiAhmadi** [comment]
another suggestion: 
```ts
type connect = boolean | 'upper' | 'lower' | 'both' // if connect is true then only connect with next knob (same as upper). 
```

```svelte

<!-- connect from 0 to 50 -->
<Slider>
    <SliderKnob connect="lower" value={50}/>
</Slider>

<!-- connect from 0 to 100 -->
<Slider>
    <SliderKnob connect="both" bind:value/>
</Slider>

<!-- connect from 50 to 100 -->
<Slider>
    <SliderKnob connect value={50}/>
    <!-- <SliderKnob connect="upper" value={50}/> -->
</Slider>


<!-- connect from 20 to 60 -->
<Slider>
    <SliderKnob connect value={20}/>
    <SliderKnob value={60}/> <!-- connect="lower" -->
</Slider>



```

**Pull request merged**
