### PR TITLE
4 initial commit for alert

### PR DESCRIPTION
**Pull request by abdolian**
- renamed `filled` to `important`
- renamed `value` to `open`
- changed the title's default value from `string empty` to `undefined`
- changed the dismissible's default value from `false` to `undefined`
- nullabled the arguments of the `classname` utils
- renamed `u-alert-end` class to `u-alert-close`
- the `alert-link` class was kept to indicate the link in alert
- remove title element when doesn't exist value for that
- all examples was synced with tabler and ubeac
- updated `start` slot to use avatar inside that without extra element

### CODE REVIEW

**Comment by pournasserian** [comment]
Please resolve these minor issues:
image

And, we should not use `classname` helper, use `<El componentName="{componentName}-body">` instead of `<div class={classname('alert-body')}>`

**Comment by pournasserian** [comment]
> * renamed `filled` to `important`
> * renamed `value` to `open`
> * changed the title's default value from `string empty` to `undefined`
> * changed the dismissible's default value from `false` to `undefined`
> * nullabled the arguments of the `classname` utils
> * renamed `u-alert-end` class to `u-alert-close`
> * the `alert-link` class was kept to indicate the link in alert
> * remove title element when doesn't exist value for that
> * all examples was synced with tabler and ubeac
> * updated `start` slot to use avatar inside that without extra element

That's great, thanks

**Comment by pournasserian** [comment]
Also review this warning:
image

**Comment by abdolian** [comment]
- added `role` to the El
- replace all `div` elements with `El`

**Pull request merged**
